### PR TITLE
changed build root image tag

### PR DESCRIPTION
**Pull request by Madhan-SWE**
changed build root image tag to 4.11 from 4.12

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
is this because you don't have the 4.12 root image yet?

**Comment by mkumatag** [comment]
@Madhan-SWE also make sure you enabled first the prow config for approval and other required plugins to allow bot to merge

**Comment by Madhan-SWE** [comment]
> is this because you don't have the 4.12 root image yet?
@mkumatag 
As of now other operators or using 4.11 image.
Can we follow the same?

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
