### PR TITLE
Changing the base image to standard openshift images

### PR DESCRIPTION
**Pull request by Madhan-SWE**
Changing the base image to standard openshift images.

### CODE REVIEW

**Comment by Madhan-SWE** [comment]
@mkumatag 
This PR should be merged to pass the ci job: **ci/rehearse/openshift/ibm-powervs-block-csi-driver-operator/main/images**
Write access is give to `Team Multi-Arch`. Please review and merge manually if there are no review comments.

**Comment by Madhan-SWE** [comment]
@mkumatag ,
Prow configuration is added. lets try to `lgtm` here if there are no comments.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
